In [1]:
import numpy as np
import torch
import pygame
import random
from torch import nn
from torch.distributions import Categorical
import torch.nn.functional as F
import copy
from collections import deque
import tqdm

colors = [
    (0, 0, 0),
    (120, 37, 179),
    (100, 179, 179),
    (80, 34, 22),
    (80, 134, 22),
    (180, 34, 22),
    (180, 34, 122),
]


pygame 2.1.0 (SDL 2.0.16, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [3]:
class Event():
    type = None
    key = None

    def __init__(self, type, key):
        self.type = type
        self.key = key

In [4]:
class Figure:
    x = 0
    y = 0

    figures = [
        [[1, 5, 9, 13], [4, 5, 6, 7]],
        [[4, 5, 9, 10], [2, 6, 5, 9]],
        [[6, 7, 9, 10], [1, 5, 6, 10]],
        [[1, 2, 5, 9], [0, 4, 5, 6], [1, 5, 9, 8], [4, 5, 6, 10]],
        [[1, 2, 6, 10], [5, 6, 7, 9], [2, 6, 10, 11], [3, 5, 6, 7]],
        [[1, 4, 5, 6], [1, 4, 5, 9], [4, 5, 6, 9], [1, 5, 6, 9]],
        [[1, 2, 5, 6]],
    ]

    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.type = random.randint(0, len(self.figures) - 1)
        self.color = 1
        self.rotation = 0

    def image(self):
        return self.figures[self.type][self.rotation]

    def rotate(self):
        self.rotation = (self.rotation + 1) % len(self.figures[self.type])


In [5]:
class Tetris:
    def __init__(self, height, width):
        self.level = 2
        self.score = 0
        self.field = []
        self.height = 0
        self.width = 0
        self.x = 100
        self.y = 60
        self.zoom = 20
        self.figure = None
    
        self.height = height
        self.width = width
        self.field = []
        self.score = 0
        self.done = False
        for i in range(height):
            new_line = []
            for j in range(width):
                new_line.append(0)
            self.field.append(new_line)
            
    def reset(self):
        self.field = []
        self.score = 0
        self.done = False
        for i in range(self.height):
            new_line = []
            for j in range(self.width):
                new_line.append(0)
            self.field.append(new_line)

    def new_figure(self):
        self.figure = Figure(3, 0)

    def intersects(self, figure):
        intersection = False
        for i in range(4):
            for j in range(4):
                if i * 4 + j in figure.image():
                    if i + figure.y > self.height - 1 or \
                            j + figure.x > self.width - 1 or \
                            j + figure.x < 0 or \
                            self.field[i + figure.y][j + figure.x] > 0:
                        intersection = True
        return intersection
    
    def step(self, figure):  
        state = copy.deepcopy(self.field)
        for i in range(4):
            for j in range(4):
                if i * 4 + j in figure.image():
                    state[i + figure.y][j + figure.x] = figure.color
#         print("/////////////////////////")
#         for row in state:
#             print(row)
        return state

    def break_lines(self):
        lines = 0
        for i in range(1, self.height):
            zeros = 0
            for j in range(self.width):
                if self.field[i][j] == 0:
                    zeros += 1
            if zeros == 0:
                lines += 1
                for i1 in range(i, 1, -1):
                    for j in range(self.width):
                        self.field[i1][j] = self.field[i1 - 1][j]
        self.score += lines ** 2

    def go_space(self):
        while not self.intersects(self.figure):
            self.figure.y += 1
        self.figure.y -= 1
        self.freeze()

    def go_down(self):
        self.figure.y += 1
        if self.intersects(self.figure):
            self.figure.y -= 1
            self.freeze()

    def freeze(self):
        for i in range(4):
            for j in range(4):
                if i * 4 + j in self.figure.image():
                    self.field[i + self.figure.y][j + self.figure.x] = self.figure.color
        self.break_lines()
        self.new_figure()
        self.done =  self.intersects(self.figure)

    def go_side(self, dx):
        old_x = self.figure.x
        self.figure.x += dx
        intersects = self.intersects(self.figure)
        if intersects:
            self.figure.x = old_x
        return intersects

    def rotate(self):
        old_rotation = self.figure.rotation
        self.figure.rotate()
        if self.intersects(self.figure):
            self.figure.rotation = old_rotation


In [6]:
class NeuralNet(nn.Module):
    def __init__(self, input_dims, hidden_dims, output_dims):
        super(NeuralNet, self).__init__()

        """ CODE HERE:
                Implement the neural network here
        """
        self.fc1 = nn.Linear(input_dims, hidden_dims)
        self.fc2 = nn.Linear(hidden_dims, hidden_dims)
        self.fc3 = nn.Linear(hidden_dims, output_dims)

    def forward(self, x):
        """ CODE HERE:
                Implement the forward propagation
        """
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

In [7]:
def get_state_properties(state):
    tower_h = []
    holes = []
    height_board = len(state)
    width_board  = len(state[0])
    lines = [1]*len(state)
    for j in range(width_board):
        tower_h.append(0)
        holes.append(0)
        top_reached = False
        for i in range(height_board):
            if state[i][j] == 0:
                if top_reached:
                    holes[j] += 1
                if lines[i] == 1:
                    lines[i] = 0
            elif state[i][j] != 0 and not top_reached:
                tower_h[j] = height_board - i
                top_reached =True
    bumps = []
    for i in range(width_board):
        bumps.append(0)
        if i != width_board-1:
            bumps[i] += abs(tower_h[i+1]-tower_h[i])
        if i != 0:
            bumps[i] += abs(tower_h[i-1]-tower_h[i])
    tower_h = np.array(tower_h) - sum(lines)
    feature = torch.tensor([sum(bumps), sum(holes), sum(tower_h), max(tower_h), sum(lines)], dtype=torch.float32)
    return feature, sum(lines)*10


def get_bfs_score(state):
    feature, _ = get_state_properties(state)
    return -feature[0].item() - 13*feature[1].item()  - feature[3].item()

def simulate(t):
    fig = Figure(3, 0)
    fig.type = t.figure.type
    fig.color = t.figure.color
    opt = float("-inf")
    opt_rotation, opt_x = 0, fig.x
    if t.intersects(fig):
        return opt_rotation, opt_x
    fig.x = -3
    for i in range(t.width + 3):
        for j in range(len(fig.figures[fig.type])):
            if not t.intersects(fig):
                while not t.intersects(fig):
                    fig.y += 1
                fig.y-=1
                possible_state = t.step(fig)
#                 score = get_bfs_score(possible_state)
                
                feature, _ = get_state_properties(possible_state)
                score = model(feature)
                if score > opt:
                    opt = score
                    opt_rotation = fig.rotation
                    opt_x = fig.x
                fig.y = 0
            fig.rotate()
        fig.x += 1
    return opt_rotation, opt_x


def run_ai(t):
    rotation, x = simulate(t)
    if t.figure.rotation != rotation:
        return [Event(pygame.KEYDOWN, pygame.K_UP)]
    elif t.figure.x < x:
        return [Event(pygame.KEYDOWN, pygame.K_RIGHT)]
    elif t.figure.x > x:
        return [Event(pygame.KEYDOWN, pygame.K_LEFT)]
    else:
        return [Event(pygame.KEYDOWN, pygame.K_SPACE)]
    return []

In [8]:
feature_len = 5
model = NeuralNet(feature_len,64,1)

# Preffered way
FILE = "model.pth"
torch.save(model, FILE)

In [ ]:
feature_len = 5
FILE = "model.pth"
# model must be created agin with parameters
model = torch.load(FILE)
model.eval()

width = 10
height = 20

env = Tetris(height, width)

learning_rate = 5e-4
gamma = 0.99
epsilon = 1
eps_dec = 1e-4
eps_min = 0.01
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()
replay_memory = deque(maxlen=30000)
scores = deque(maxlen=100)
n_episodes = 100000
batch_size = 500

def simulate_RL(t, isRandom):
    fig = Figure(3, 0)
    reward, best_state, best_feature, done = -300, None, torch.zeros(feature_len), True
    if t.intersects(fig):
        return best_state, best_feature, reward, done
    fig.x = -3
    fig.type = t.figure.type
    fig.color = t.figure.color
    opt = float("-inf")
    states, features, rewards = [], [], []
    for i in range(t.width + 3):
        for j in range(len(fig.figures[fig.type])):
            if not t.intersects(fig):
                while not t.intersects(fig):
                    fig.y += 1
                fig.y-=1
                done = False
                state = t.step(fig)
                feature, r = get_state_properties(state)
                score = model(feature)
                if score > opt:
                    opt = score
                    reward = r
                    best_state = state
                    best_feature = feature
                states.append(state)
                features.append(feature)
                rewards.append(r)
                fig.y = 0
            fig.rotate()
        fig.x += 1
    if isRandom and not done:
        index = random.randint(0, len(states) - 1)
        return states[index], features[index], rewards[index], done
    return best_state, best_feature, reward, done

pbar = tqdm.trange(n_episodes)
for t in pbar:
    env.reset()
    feature = torch.zeros(feature_len)
    epsilon =  epsilon - eps_dec \
            if epsilon > eps_min else eps_min
    score = 0
    while True:
        random_action =  random.random() <= epsilon
        env.new_figure()
        next_state, next_feature, reward, done = simulate_RL(env, random_action)
        score += reward
        
        replay_memory.append((feature, reward, next_feature, done))
        feature = next_feature
        batch = random.sample(replay_memory, min(len(replay_memory), batch_size))
        feature_batch, reward_batch, next_feature_batch, done_batch = zip(*batch)
        feature_batch = torch.stack(tuple(feat for feat in feature_batch))
        reward_batch = torch.from_numpy(np.array(reward_batch, dtype=np.float32)[:, None])
        next_feature_batch = torch.stack(tuple(feat for feat in next_feature_batch))

        q_values = model(feature_batch)
        with torch.no_grad():
            next_prediction_batch = model(next_feature_batch)

        y_batch = torch.cat(
                tuple(reward if done else reward + 1 + gamma * prediction for reward, done, prediction in
                      zip(reward_batch, done_batch, next_prediction_batch)))[:, None]
        optimizer.zero_grad()
        loss = criterion(q_values, y_batch)
        loss.backward()
        optimizer.step()
        if done:
            scores.append(score)
#             print("///////////Game Over//////////////////")
            break
#         print()
#         for row in env.field:
#             print(row)
#         print(next_feature)
        env.field = next_state
        env.break_lines()
    if t%100 ==0:
        print(np.mean(scores), epsilon)
    if t%200 == 0:
        torch.save(model, FILE)


  0%|                                                                             | 2/100000 [00:00<5:02:15,  5.51it/s]

-300.0 0.9999


  0%|                                                                          | 101/100000 [00:37<10:43:18,  2.59it/s]

-299.9 0.9899000000000011


  0%|▏                                                                          | 201/100000 [01:17<9:28:59,  2.92it/s]

-299.9 0.9799000000000022


  0%|▏                                                                         | 301/100000 [01:58<10:26:19,  2.65it/s]

-299.8 0.9699000000000033


  0%|▎                                                                         | 401/100000 [02:38<10:47:07,  2.57it/s]

-299.9 0.9599000000000044


  1%|▎                                                                         | 501/100000 [03:18<10:44:23,  2.57it/s]

-299.5 0.9499000000000055


  1%|▍                                                                         | 601/100000 [04:01<13:20:36,  2.07it/s]

-299.6 0.9399000000000066


  1%|▌                                                                         | 701/100000 [04:42<12:19:57,  2.24it/s]

-299.4 0.9299000000000077


  1%|▌                                                                         | 801/100000 [05:25<11:00:28,  2.50it/s]

-299.3 0.9199000000000088


  1%|▋                                                                         | 901/100000 [06:06<11:26:25,  2.41it/s]

-300.0 0.9099000000000099


  1%|▋                                                                        | 1001/100000 [06:49<12:05:53,  2.27it/s]

-299.3 0.899900000000011


  1%|▊                                                                        | 1101/100000 [07:32<11:13:17,  2.45it/s]

-298.9 0.8899000000000121


  1%|▉                                                                        | 1201/100000 [08:17<12:02:01,  2.28it/s]

-299.7 0.8799000000000132


  1%|▉                                                                        | 1301/100000 [09:01<13:36:37,  2.01it/s]

-299.1 0.8699000000000143


  1%|█                                                                        | 1401/100000 [09:47<11:42:20,  2.34it/s]

-299.3 0.8599000000000154


  2%|█                                                                        | 1501/100000 [10:32<11:52:06,  2.31it/s]

-298.9 0.8499000000000165


  2%|█▏                                                                       | 1601/100000 [11:18<11:49:52,  2.31it/s]

-298.5 0.8399000000000176


  2%|█▏                                                                       | 1701/100000 [12:03<12:04:19,  2.26it/s]

-298.9 0.8299000000000187


  2%|█▎                                                                       | 1801/100000 [12:48<12:54:05,  2.11it/s]

-298.6 0.8199000000000198


  2%|█▍                                                                       | 1901/100000 [13:34<12:50:55,  2.12it/s]

-298.5 0.8099000000000209


  2%|█▍                                                                       | 2001/100000 [14:22<13:15:21,  2.05it/s]

-298.1 0.799900000000022


  2%|█▌                                                                       | 2101/100000 [15:08<12:39:07,  2.15it/s]

-298.3 0.7899000000000231


  2%|█▌                                                                       | 2201/100000 [15:57<13:07:24,  2.07it/s]

-297.6 0.7799000000000242


  2%|█▋                                                                       | 2301/100000 [16:45<14:06:53,  1.92it/s]

-298.0 0.7699000000000253


  2%|█▊                                                                       | 2401/100000 [17:34<13:17:57,  2.04it/s]

-298.1 0.7599000000000264


  3%|█▊                                                                       | 2501/100000 [18:21<11:38:43,  2.33it/s]

-298.1 0.7499000000000275


  3%|█▉                                                                       | 2601/100000 [19:11<13:18:26,  2.03it/s]

-296.6 0.7399000000000286


  3%|█▉                                                                       | 2701/100000 [20:02<14:17:57,  1.89it/s]

-296.5 0.7299000000000297


  3%|██                                                                       | 2801/100000 [20:52<13:54:08,  1.94it/s]

-296.5 0.7199000000000308


  3%|██                                                                       | 2901/100000 [21:42<14:56:44,  1.80it/s]

-295.3 0.709900000000032


  3%|██▏                                                                      | 3001/100000 [22:33<14:27:05,  1.86it/s]

-296.1 0.699900000000033


  3%|██▎                                                                      | 3101/100000 [23:24<12:22:59,  2.17it/s]

-295.7 0.6899000000000342


  3%|██▎                                                                      | 3201/100000 [24:19<16:34:06,  1.62it/s]

-293.9 0.6799000000000353


  3%|██▍                                                                      | 3301/100000 [25:13<14:44:38,  1.82it/s]

-295.6 0.6699000000000364


  3%|██▍                                                                      | 3401/100000 [26:09<13:04:15,  2.05it/s]

-295.0 0.6599000000000375


  4%|██▌                                                                      | 3501/100000 [27:05<14:00:07,  1.91it/s]

-293.8 0.6499000000000386


  4%|██▋                                                                      | 3601/100000 [28:01<14:19:15,  1.87it/s]

-294.5 0.6399000000000397


  4%|██▋                                                                      | 3701/100000 [28:59<17:35:10,  1.52it/s]

-293.5 0.6299000000000408


  4%|██▊                                                                      | 3801/100000 [29:55<15:50:27,  1.69it/s]

-293.5 0.6199000000000419


  4%|██▊                                                                      | 3901/100000 [30:54<16:06:14,  1.66it/s]

-292.5 0.609900000000043


  4%|██▉                                                                      | 4001/100000 [31:54<15:15:59,  1.75it/s]

-290.5 0.5999000000000441


  4%|██▉                                                                      | 4101/100000 [32:53<16:44:52,  1.59it/s]

-291.6 0.5899000000000452


  4%|███                                                                      | 4201/100000 [33:59<17:23:22,  1.53it/s]

-288.1 0.5799000000000463


  4%|███▏                                                                     | 4301/100000 [35:05<16:24:14,  1.62it/s]

-286.8 0.5699000000000474


  4%|███▏                                                                     | 4401/100000 [36:06<15:22:25,  1.73it/s]

-291.9 0.5599000000000485


  5%|███▎                                                                     | 4501/100000 [37:10<20:02:52,  1.32it/s]

-288.3 0.5499000000000496


  5%|███▎                                                                     | 4601/100000 [38:16<17:58:20,  1.47it/s]

-288.0 0.5399000000000507


  5%|███▍                                                                     | 4701/100000 [39:19<15:00:26,  1.76it/s]

-288.3 0.5299000000000518


  5%|███▌                                                                     | 4801/100000 [40:26<20:00:23,  1.32it/s]

-286.7 0.5199000000000529


  5%|███▌                                                                     | 4901/100000 [41:33<14:27:41,  1.83it/s]

-284.8 0.509900000000054


  5%|███▋                                                                     | 5001/100000 [42:42<16:13:51,  1.63it/s]

-283.7 0.4999000000000551


  5%|███▋                                                                     | 5101/100000 [43:50<16:46:59,  1.57it/s]

-285.5 0.4899000000000562


  5%|███▊                                                                     | 5201/100000 [45:00<18:42:30,  1.41it/s]

-282.6 0.4799000000000573


  5%|███▊                                                                     | 5301/100000 [46:12<18:08:44,  1.45it/s]

-281.3 0.4699000000000584


  5%|███▉                                                                     | 5401/100000 [47:24<21:54:08,  1.20it/s]

-283.4 0.4599000000000595


  6%|████                                                                     | 5501/100000 [48:37<18:15:56,  1.44it/s]

-280.1 0.4499000000000606


  6%|████                                                                     | 5601/100000 [49:50<18:39:03,  1.41it/s]

-281.1 0.4399000000000617


  6%|████▏                                                                    | 5701/100000 [51:08<19:22:29,  1.35it/s]

-276.5 0.4299000000000628


  6%|████▏                                                                    | 5801/100000 [52:26<19:17:04,  1.36it/s]

-273.9 0.4199000000000639


  6%|████▎                                                                    | 5901/100000 [53:44<22:15:31,  1.17it/s]

-273.6 0.409900000000065


  6%|████▍                                                                    | 6001/100000 [55:04<19:28:57,  1.34it/s]

-269.5 0.3999000000000661


  6%|████▍                                                                    | 6101/100000 [56:26<20:33:14,  1.27it/s]

-272.7 0.3899000000000672


  6%|████▌                                                                    | 6201/100000 [57:55<20:12:39,  1.29it/s]

-269.1 0.3799000000000683


  6%|████▌                                                                    | 6301/100000 [59:26<23:41:46,  1.10it/s]

-269.5 0.3699000000000694


  6%|████▌                                                                  | 6401/100000 [1:01:01<20:41:02,  1.26it/s]

-265.2 0.3599000000000705


  7%|████▌                                                                  | 6501/100000 [1:02:40<27:05:40,  1.04s/it]

-259.2 0.3499000000000716


  7%|████▋                                                                  | 6601/100000 [1:04:31<24:59:56,  1.04it/s]

-260.3 0.3399000000000727


  7%|████▊                                                                  | 6701/100000 [1:06:11<21:23:20,  1.21it/s]

-258.7 0.3299000000000738


  7%|████▊                                                                  | 6801/100000 [1:07:38<26:39:04,  1.03s/it]

-257.3 0.3199000000000749


  7%|████▉                                                                  | 6901/100000 [1:09:11<21:33:21,  1.20it/s]

-249.4 0.309900000000076


  7%|████▉                                                                  | 7001/100000 [1:10:42<26:04:28,  1.01s/it]

-254.9 0.2999000000000771


  7%|█████                                                                  | 7101/100000 [1:12:20<23:38:46,  1.09it/s]

-240.9 0.2899000000000782


  7%|█████                                                                  | 7201/100000 [1:13:57<24:07:43,  1.07it/s]

-242.7 0.2799000000000793


  7%|█████▏                                                                 | 7301/100000 [1:15:38<25:09:32,  1.02it/s]

-237.1 0.2699000000000804


  7%|█████▎                                                                 | 7401/100000 [1:17:18<24:58:27,  1.03it/s]

-238.7 0.2599000000000815


  8%|█████▎                                                                 | 7501/100000 [1:19:06<28:39:43,  1.12s/it]

-225.7 0.2499000000000826


  8%|█████▍                                                                 | 7601/100000 [1:20:54<30:12:50,  1.18s/it]

-225.5 0.2399000000000837


  8%|█████▍                                                                 | 7701/100000 [1:22:45<28:48:02,  1.12s/it]

-214.6 0.22990000000008481


  8%|█████▌                                                                 | 7801/100000 [1:24:40<31:23:39,  1.23s/it]

-215.2 0.21990000000008592


  8%|█████▌                                                                 | 7901/100000 [1:26:39<27:38:37,  1.08s/it]

-205.1 0.20990000000008702


  8%|█████▋                                                                 | 8001/100000 [1:28:38<34:13:29,  1.34s/it]

-205.2 0.19990000000008812


  8%|█████▊                                                                 | 8101/100000 [1:30:52<39:52:29,  1.56s/it]

-175.7 0.18990000000008922


  8%|█████▊                                                                 | 8201/100000 [1:33:11<31:40:39,  1.24s/it]

-166.6 0.17990000000009032


  8%|█████▉                                                                 | 8301/100000 [1:35:29<36:17:54,  1.43s/it]

-166.8 0.16990000000009142


  8%|█████▉                                                                 | 8401/100000 [1:37:51<36:13:09,  1.42s/it]

-163.4 0.15990000000009252


  9%|██████                                                                 | 8501/100000 [1:40:22<38:05:01,  1.50s/it]

-145.7 0.14990000000009363


  9%|██████                                                                 | 8601/100000 [1:43:00<48:37:47,  1.92s/it]

-133.1 0.13990000000009473


  9%|██████▏                                                                | 8701/100000 [1:45:46<41:45:48,  1.65s/it]

-118.5 0.12990000000009583


  9%|██████▏                                                                | 8801/100000 [1:48:34<40:55:39,  1.62s/it]

-118.3 0.11990000000009622


  9%|██████▎                                                                | 8901/100000 [1:51:37<57:51:00,  2.29s/it]

-100.8 0.10990000000009593


  9%|██████▍                                                                | 9001/100000 [1:54:53<46:51:06,  1.85s/it]

-62.0 0.09990000000009565


  9%|██████▍                                                                | 9101/100000 [1:58:14<61:51:23,  2.45s/it]

-51.8 0.08990000000009536


  9%|██████▌                                                                | 9201/100000 [2:01:53<59:11:01,  2.35s/it]

-17.9 0.07990000000009508


  9%|██████▌                                                                | 9301/100000 [2:06:51<76:01:00,  3.02s/it]

59.4 0.06990000000009479


  9%|██████▋                                                                | 9401/100000 [2:12:32<61:51:50,  2.46s/it]

68.9 0.0599000000000945


 10%|██████▋                                                                | 9501/100000 [2:18:41<97:19:43,  3.87s/it]

132.1 0.049900000000094216


 10%|██████▋                                                               | 9601/100000 [2:26:32<161:12:30,  6.42s/it]

205.7 0.03990000000009393


 10%|██████▊                                                               | 9701/100000 [10:35:24<66:31:16,  2.65s/it]

288.0 0.029900000000093692


 10%|██████▊                                                              | 9801/100000 [10:43:04<100:59:46,  4.03s/it]

273.0 0.019900000000093752


 10%|██████▊                                                              | 9860/100000 [10:49:32<212:20:00,  8.48s/it]

In [20]:
n_episodes = 1
pbar = tqdm.trange(n_episodes)
for t in pbar:
    env.reset() 
    feature = torch.zeros(feature_len).float()
    epsilon =  epsilon - eps_dec \
            if epsilon > eps_min else eps_min
    score = 0
    while True:
        random_action =  random.random() <= epsilon
        env.new_figure()
        next_state, next_feature, reward, done = simulate_RL(env, random_action)
        score += reward
        replay_memory.append((feature, reward, next_feature, done))
        if done:
            scores.append(score)
            print("///////////Game Over//////////////////")
            break
        env.field = next_state
        env.break_lines()
        print()
        for row in env.field:
            print(row)
        print(next_feature)
        feature = next_feature
print(score)

  0%|                                                                                            | 0/1 [00:00<?, ?it/s]


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
tensor([4., 0., 4., 2., 0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0

tensor([ 8.,  7., 57.,  7.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 0, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
tensor([ 8.,  7., 61.,  7.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


tensor([ 4., 10., 80.,  9.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 1, 1]
[1, 1, 1, 0, 1, 1, 0, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
tensor([ 6., 10., 74.,  9.,  1.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


[0, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
tensor([ 8., 10., 84.,  9.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
tensor([ 8., 10., 88.,  9.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.27it/s]

tensor([ 24.,  14., 144.,  20.,   0.])

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 1, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
tensor([ 32.,  14., 148.,  20.,   0.])

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 1, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1,

In [37]:
t = Tetris(20,10)

while True:
    sentence = input("Input:")
    if sentence =="q":
        break
    if t.figure is None:
        t.new_figure()
    if sentence == "u":
        t.rotate()
    elif sentence == "l":
        t.go_side(-1)
    elif sentence == "r":
        t.go_side(1)
    elif sentence == "s":
        t.go_space()
    print(simulate(t))
    t.go_down()
    print()
    for row in t.field:
        print(row)

Input:q


In [36]:
# Initialize the game engine
pygame.init()

# Define some colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GRAY = (128, 128, 128)

size = (400, 500)
screen = pygame.display.set_mode(size)

pygame.display.set_caption("Tetris")

# Loop until the user clicks the close button.
done = False
clock = pygame.time.Clock()
fps = 10
game = Tetris(20, 10)
counter = 0

pressing_down = False

while not done:
    if game.figure is None:
        game.new_figure()
    counter += 1
    if counter > 100000:
        counter = 0

    if counter % (fps // game.level // 2) == 0 or pressing_down:
        if not game.done:
            game.go_down()

    for event in list(pygame.event.get()) + run_ai(game):
        if event.type == pygame.QUIT:
            done = True
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_UP:
                game.rotate()
            if event.key == pygame.K_DOWN:
                pressing_down = True
            if event.key == pygame.K_LEFT:
                game.go_side(-1)
            if event.key == pygame.K_RIGHT:
                game.go_side(1)
            if event.key == pygame.K_SPACE:
                game.go_space()
            if event.key == pygame.K_ESCAPE:
                game.__init__(20, 10)

    if event.type == pygame.KEYUP:
            if event.key == pygame.K_DOWN:
                pressing_down = False

    screen.fill(WHITE)

    for i in range(game.height):
        for j in range(game.width):
            pygame.draw.rect(screen, GRAY, [game.x + game.zoom * j, game.y + game.zoom * i, game.zoom, game.zoom], 1)
            if game.field[i][j] > 0:
                pygame.draw.rect(screen, colors[game.field[i][j]],
                                 [game.x + game.zoom * j + 1, game.y + game.zoom * i + 1, game.zoom - 2, game.zoom - 1])
    
    if game.figure is not None:
        for i in range(4):
            for j in range(4):
                p = i * 4 + j
                if p in game.figure.image():
                    pygame.draw.rect(screen, colors[game.figure.color],
                                     [game.x + game.zoom * (j + game.figure.x) + 1,
                                      game.y + game.zoom * (i + game.figure.y) + 1,
                                      game.zoom - 2, game.zoom - 2])

    font = pygame.font.SysFont('Calibri', 25, True, False)
    font1 = pygame.font.SysFont('Calibri', 65, True, False)
    text = font.render("Score: " + str(game.score), True, BLACK)
    text_game_over = font1.render("Game Over", True, (255, 125, 0))
    text_game_over1 = font1.render("Press ESC", True, (255, 215, 0))

    screen.blit(text, [0, 0])
    if game.done:
        screen.blit(text_game_over, [20, 200])
        screen.blit(text_game_over1, [25, 265])

    pygame.display.flip()
    clock.tick(fps)

pygame.quit()