In [1]:
import numpy as np
import torch
import pygame
import random
from torch import nn
from torch.distributions import Categorical
import torch.nn.functional as F
import copy
from collections import deque
import tqdm

colors = [
    (0, 0, 0),
    (120, 37, 179),
    (100, 179, 179),
    (80, 34, 22),
    (80, 134, 22),
    (180, 34, 22),
    (180, 34, 122),
]


pygame 2.1.0 (SDL 2.0.16, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [3]:
class Event():
    type = None
    key = None

    def __init__(self, type, key):
        self.type = type
        self.key = key

In [4]:
class Figure:
    x = 0
    y = 0

    figures = [
        [[1, 5, 9, 13], [4, 5, 6, 7]],
        [[4, 5, 9, 10], [2, 6, 5, 9]],
        [[6, 7, 9, 10], [1, 5, 6, 10]],
        [[1, 2, 5, 9], [0, 4, 5, 6], [1, 5, 9, 8], [4, 5, 6, 10]],
        [[1, 2, 6, 10], [5, 6, 7, 9], [2, 6, 10, 11], [3, 5, 6, 7]],
        [[1, 4, 5, 6], [1, 4, 5, 9], [4, 5, 6, 9], [1, 5, 6, 9]],
        [[1, 2, 5, 6]],
    ]

    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.type = random.randint(0, len(self.figures) - 1)
        self.color = 1
        self.rotation = 0

    def image(self):
        return self.figures[self.type][self.rotation]

    def rotate(self):
        self.rotation = (self.rotation + 1) % len(self.figures[self.type])


In [5]:
class Tetris:
    def __init__(self, height, width):
        self.level = 2
        self.score = 0
        self.field = []
        self.height = 0
        self.width = 0
        self.x = 100
        self.y = 60
        self.zoom = 20
        self.figure = None
    
        self.height = height
        self.width = width
        self.field = []
        self.score = 0
        self.done = False
        for i in range(height):
            new_line = []
            for j in range(width):
                new_line.append(0)
            self.field.append(new_line)
            
    def reset(self):
        self.field = []
        self.score = 0
        self.done = False
        for i in range(self.height):
            new_line = []
            for j in range(self.width):
                new_line.append(0)
            self.field.append(new_line)

    def new_figure(self):
        self.figure = Figure(3, 0)

    def intersects(self, figure):
        intersection = False
        for i in range(4):
            for j in range(4):
                if i * 4 + j in figure.image():
                    if i + figure.y > self.height - 1 or \
                            j + figure.x > self.width - 1 or \
                            j + figure.x < 0 or \
                            self.field[i + figure.y][j + figure.x] > 0:
                        intersection = True
        return intersection
    
    def step(self, figure):  
        state = copy.deepcopy(self.field)
        for i in range(4):
            for j in range(4):
                if i * 4 + j in figure.image():
                    state[i + figure.y][j + figure.x] = figure.color
#         print("/////////////////////////")
#         for row in state:
#             print(row)
        return state

    def break_lines(self):
        lines = 0
        for i in range(1, self.height):
            zeros = 0
            for j in range(self.width):
                if self.field[i][j] == 0:
                    zeros += 1
            if zeros == 0:
                lines += 1
                for i1 in range(i, 1, -1):
                    for j in range(self.width):
                        self.field[i1][j] = self.field[i1 - 1][j]
        self.score += lines ** 2

    def go_space(self):
        while not self.intersects(self.figure):
            self.figure.y += 1
        self.figure.y -= 1
        self.freeze()

    def go_down(self):
        self.figure.y += 1
        if self.intersects(self.figure):
            self.figure.y -= 1
            self.freeze()

    def freeze(self):
        for i in range(4):
            for j in range(4):
                if i * 4 + j in self.figure.image():
                    self.field[i + self.figure.y][j + self.figure.x] = self.figure.color
        self.break_lines()
        self.new_figure()
        self.done =  self.intersects(self.figure)

    def go_side(self, dx):
        old_x = self.figure.x
        self.figure.x += dx
        intersects = self.intersects(self.figure)
        if intersects:
            self.figure.x = old_x
        return intersects

    def rotate(self):
        old_rotation = self.figure.rotation
        self.figure.rotate()
        if self.intersects(self.figure):
            self.figure.rotation = old_rotation


In [6]:
class NeuralNet(nn.Module):
    def __init__(self, input_dims, hidden_dims, output_dims):
        super(NeuralNet, self).__init__()

        """ CODE HERE:
                Implement the neural network here
        """
        self.fc1 = nn.Linear(input_dims, hidden_dims)
        self.fc2 = nn.Linear(hidden_dims, hidden_dims)
        self.fc3 = nn.Linear(hidden_dims, output_dims)

    def forward(self, x):
        """ CODE HERE:
                Implement the forward propagation
        """
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

In [7]:
def get_state_properties(state):
    tower_h = []
    holes = []
    height_board = len(state)
    width_board  = len(state[0])
    lines = [1]*len(state)
    for j in range(width_board):
        tower_h.append(0)
        holes.append(0)
        top_reached = False
        for i in range(height_board):
            if state[i][j] == 0:
                if top_reached:
                    holes[j] += 1
                if lines[i] == 1:
                    lines[i] = 0
            elif state[i][j] != 0 and not top_reached:
                tower_h[j] = height_board - i
                top_reached =True
    bumps = []
    for i in range(width_board):
        bumps.append(0)
        if i != width_board-1:
            bumps[i] += abs(tower_h[i+1]-tower_h[i])
        if i != 0:
            bumps[i] += abs(tower_h[i-1]-tower_h[i])
    tower_h = np.array(tower_h) - sum(lines)
    feature = torch.tensor([sum(bumps), sum(holes), sum(tower_h), max(tower_h), sum(lines)], dtype=torch.float32)
    return feature, sum(lines)*10


def get_bfs_score(state):
    feature, _ = get_state_properties(state)
    return -feature[0].item() - 13*feature[1].item()  - feature[3].item()

def simulate(t):
    fig = Figure(3, 0)
    fig.type = t.figure.type
    fig.color = t.figure.color
    opt = float("-inf")
    opt_rotation, opt_x = 0, fig.x
    if t.intersects(fig):
        return opt_rotation, opt_x
    fig.x = -3
    for i in range(t.width + 3):
        for j in range(len(fig.figures[fig.type])):
            if not t.intersects(fig):
                while not t.intersects(fig):
                    fig.y += 1
                fig.y-=1
                possible_state = t.step(fig)
#                 score = get_bfs_score(possible_state)
                
                feature, _ = get_state_properties(possible_state)
                score = model(feature)
                if score > opt:
                    opt = score
                    opt_rotation = fig.rotation
                    opt_x = fig.x
                fig.y = 0
            fig.rotate()
        fig.x += 1
    return opt_rotation, opt_x


def run_ai(t):
    rotation, x = simulate(t)
    if t.figure.rotation != rotation:
        return [Event(pygame.KEYDOWN, pygame.K_UP)]
    elif t.figure.x < x:
        return [Event(pygame.KEYDOWN, pygame.K_RIGHT)]
    elif t.figure.x > x:
        return [Event(pygame.KEYDOWN, pygame.K_LEFT)]
    else:
        return [Event(pygame.KEYDOWN, pygame.K_SPACE)]
    return []

In [8]:
feature_len = 5
model = NeuralNet(feature_len,128,1)

# Preffered way
FILE = "model.pth"
torch.save(model, FILE)

NeuralNet(
  (fc1): Linear(in_features=5, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=1, bias=True)
)

In [17]:
feature_len = 5
FILE = "model.pth"
# model must be created agin with parameters
model = torch.load(FILE)
model.eval()

width = 10
height = 20

env = Tetris(height, width)

learning_rate = 5e-4
gamma = 0.99
epsilon = 0.01
eps_dec = 1e-4
eps_min = 0.01
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()
replay_memory = deque(maxlen=30000)
scores = deque(maxlen=100)
n_episodes = 100000
batch_size = 512

def simulate_RL(t, isRandom):
    fig = Figure(3, 0)
    reward, best_state, best_feature, done = -300, None, torch.zeros(feature_len), True
    if t.intersects(fig):
        return best_state, best_feature, reward, done
    fig.x = -3
    fig.type = t.figure.type
    fig.color = t.figure.color
    opt = float("-inf")
    states, features, rewards = [], [], []
    for i in range(t.width + 3):
        for j in range(len(fig.figures[fig.type])):
            if not t.intersects(fig):
                while not t.intersects(fig):
                    fig.y += 1
                fig.y-=1
                done = False
                state = t.step(fig)
                feature, r = get_state_properties(state)
                score = model(feature)
                if score > opt:
                    opt = score
                    reward = r
                    best_state = state
                    best_feature = feature
                states.append(state)
                features.append(feature)
                rewards.append(r)
                fig.y = 0
            fig.rotate()
        fig.x += 1
    if isRandom and not done:
        index = random.randint(0, len(states) - 1)
        return states[index], features[index], rewards[index], done
    return best_state, best_feature, reward, done

pbar = tqdm.trange(n_episodes)
for t in pbar:
    env.reset()
    feature = torch.zeros(feature_len)
    epsilon =  epsilon - eps_dec \
            if epsilon > eps_min else eps_min
    score = 0
    while True:
        random_action =  random.random() <= epsilon
        env.new_figure()
        next_state, next_feature, reward, done = simulate_RL(env, random_action)
        score += reward
        
        replay_memory.append((feature, reward, next_feature, done))
        feature = next_feature
        batch = random.sample(replay_memory, min(len(replay_memory), batch_size))
        feature_batch, reward_batch, next_feature_batch, done_batch = zip(*batch)
        feature_batch = torch.stack(tuple(feat for feat in feature_batch))
        reward_batch = torch.from_numpy(np.array(reward_batch, dtype=np.float32)[:, None])
        next_feature_batch = torch.stack(tuple(feat for feat in next_feature_batch))

        q_values = model(feature_batch)
        with torch.no_grad():
            next_prediction_batch = model(next_feature_batch)

        y_batch = torch.cat(
                tuple(reward if done else reward + 1 + gamma * prediction for reward, done, prediction in
                      zip(reward_batch, done_batch, next_prediction_batch)))[:, None]
        optimizer.zero_grad()
        loss = criterion(q_values, y_batch)
        loss.backward()
        optimizer.step()
        if done:
            scores.append(score)
#             print("///////////Game Over//////////////////")
            break
#         print()
#         for row in env.field:
#             print(row)
#         print(next_feature)
        env.field = next_state
        env.break_lines()
    if t%100 ==0:
        print(np.mean(scores), epsilon)
    if t%200 == 0:
        torch.save(model, FILE)


  0%|                                                                             | 2/100000 [00:00<4:45:56,  5.83it/s]

-300.0 0.9999


  0%|                                                                          | 101/100000 [00:37<12:40:38,  2.19it/s]

-299.9 0.9899000000000011


  0%|▏                                                                         | 201/100000 [01:19<11:51:00,  2.34it/s]

-299.4 0.9799000000000022


  0%|▏                                                                         | 301/100000 [02:02<12:07:56,  2.28it/s]

-299.7 0.9699000000000033


  0%|▎                                                                         | 401/100000 [02:43<12:17:34,  2.25it/s]

-299.9 0.9599000000000044


  1%|▎                                                                         | 501/100000 [03:25<10:56:32,  2.53it/s]

-299.5 0.9499000000000055


  1%|▍                                                                         | 601/100000 [04:07<10:50:08,  2.55it/s]

-299.6 0.9399000000000066


  1%|▌                                                                         | 701/100000 [04:50<12:23:21,  2.23it/s]

-299.4 0.9299000000000077


  1%|▌                                                                         | 801/100000 [05:33<12:18:35,  2.24it/s]

-299.7 0.9199000000000088


  1%|▋                                                                         | 901/100000 [06:16<12:46:27,  2.15it/s]

-299.3 0.9099000000000099


  1%|▋                                                                        | 1001/100000 [07:00<11:45:36,  2.34it/s]

-299.4 0.899900000000011


  1%|▊                                                                        | 1101/100000 [07:45<12:11:05,  2.25it/s]

-299.3 0.8899000000000121


  1%|▉                                                                        | 1201/100000 [08:29<13:32:04,  2.03it/s]

-299.3 0.8799000000000132


  1%|▉                                                                        | 1301/100000 [09:16<12:59:37,  2.11it/s]

-299.3 0.8699000000000143


  1%|█                                                                        | 1401/100000 [10:02<13:11:56,  2.08it/s]

-298.2 0.8599000000000154


  2%|█                                                                        | 1501/100000 [10:50<11:44:32,  2.33it/s]

-298.2 0.8499000000000165


  2%|█▏                                                                       | 1601/100000 [11:37<12:43:54,  2.15it/s]

-298.1 0.8399000000000176


  2%|█▏                                                                       | 1701/100000 [12:25<15:31:55,  1.76it/s]

-298.6 0.8299000000000187


  2%|█▎                                                                       | 1801/100000 [13:13<11:53:15,  2.29it/s]

-297.8 0.8199000000000198


  2%|█▍                                                                       | 1901/100000 [14:03<13:30:05,  2.02it/s]

-298.4 0.8099000000000209


  2%|█▍                                                                       | 2001/100000 [14:52<14:30:53,  1.88it/s]

-298.5 0.799900000000022


  2%|█▌                                                                       | 2101/100000 [15:40<12:55:52,  2.10it/s]

-298.2 0.7899000000000231


  2%|█▌                                                                       | 2201/100000 [16:32<13:31:53,  2.01it/s]

-297.5 0.7799000000000242


  2%|█▋                                                                       | 2301/100000 [17:21<13:42:05,  1.98it/s]

-298.4 0.7699000000000253


  2%|█▊                                                                       | 2401/100000 [18:12<12:25:01,  2.18it/s]

-296.7 0.7599000000000264


  3%|█▊                                                                       | 2501/100000 [19:05<14:24:36,  1.88it/s]

-297.1 0.7499000000000275


  3%|█▉                                                                       | 2601/100000 [19:57<14:38:40,  1.85it/s]

-296.8 0.7399000000000286


  3%|█▉                                                                       | 2701/100000 [20:48<15:45:20,  1.72it/s]

-297.4 0.7299000000000297


  3%|██                                                                       | 2801/100000 [21:40<16:04:29,  1.68it/s]

-296.5 0.7199000000000308


  3%|██                                                                       | 2901/100000 [22:31<13:05:14,  2.06it/s]

-297.6 0.709900000000032


  3%|██▏                                                                      | 3001/100000 [23:24<13:46:10,  1.96it/s]

-295.8 0.699900000000033


  3%|██▎                                                                      | 3101/100000 [24:18<13:19:32,  2.02it/s]

-296.3 0.6899000000000342


  3%|██▎                                                                      | 3201/100000 [25:12<12:54:34,  2.08it/s]

-295.3 0.6799000000000353


  3%|██▍                                                                      | 3301/100000 [26:07<15:55:24,  1.69it/s]

-296.1 0.6699000000000364


  3%|██▍                                                                      | 3401/100000 [27:03<16:02:42,  1.67it/s]

-295.1 0.6599000000000375


  4%|██▌                                                                      | 3501/100000 [28:05<15:36:21,  1.72it/s]

-294.1 0.6499000000000386


  4%|██▋                                                                      | 3601/100000 [29:02<14:16:08,  1.88it/s]

-294.1 0.6399000000000397


  4%|██▋                                                                      | 3701/100000 [30:00<15:14:50,  1.75it/s]

-293.4 0.6299000000000408


  4%|██▊                                                                      | 3801/100000 [30:58<16:07:52,  1.66it/s]

-293.3 0.6199000000000419


  4%|██▊                                                                      | 3901/100000 [32:02<17:07:16,  1.56it/s]

-290.5 0.609900000000043


  4%|██▉                                                                      | 4001/100000 [33:01<12:37:47,  2.11it/s]

-292.8 0.5999000000000441


  4%|██▉                                                                      | 4101/100000 [34:04<16:22:26,  1.63it/s]

-291.7 0.5899000000000452


  4%|███                                                                      | 4201/100000 [35:06<15:42:03,  1.69it/s]

-290.4 0.5799000000000463


  4%|███▏                                                                     | 4301/100000 [36:10<16:15:31,  1.63it/s]

-288.8 0.5699000000000474


  4%|███▏                                                                     | 4401/100000 [37:15<16:14:57,  1.63it/s]

-289.9 0.5599000000000485


  5%|███▎                                                                     | 4501/100000 [38:19<17:56:36,  1.48it/s]

-287.8 0.5499000000000496


  5%|███▎                                                                     | 4601/100000 [39:22<16:29:18,  1.61it/s]

-289.0 0.5399000000000507


  5%|███▍                                                                     | 4701/100000 [40:29<21:40:13,  1.22it/s]

-285.9 0.5299000000000518


  5%|███▌                                                                     | 4801/100000 [41:37<16:25:55,  1.61it/s]

-285.7 0.5199000000000529


  5%|███▌                                                                     | 4901/100000 [42:49<18:30:52,  1.43it/s]

-286.5 0.509900000000054


  5%|███▋                                                                     | 5001/100000 [43:55<17:04:26,  1.55it/s]

-287.3 0.4999000000000551


  5%|███▋                                                                     | 5101/100000 [45:02<19:34:51,  1.35it/s]

-284.6 0.4899000000000562


  5%|███▊                                                                     | 5201/100000 [46:11<20:46:39,  1.27it/s]

-284.5 0.4799000000000573


  5%|███▊                                                                     | 5301/100000 [47:20<17:30:43,  1.50it/s]

-282.7 0.4699000000000584


  5%|███▉                                                                     | 5401/100000 [48:33<16:46:12,  1.57it/s]

-278.9 0.4599000000000595


  6%|████                                                                     | 5501/100000 [49:44<21:58:22,  1.19it/s]

-281.9 0.4499000000000606


  6%|████                                                                     | 5601/100000 [50:56<20:56:22,  1.25it/s]

-280.3 0.4399000000000617


  6%|████▏                                                                    | 5701/100000 [52:09<18:15:07,  1.44it/s]

-279.3 0.4299000000000628


  6%|████▏                                                                    | 5801/100000 [53:25<18:56:06,  1.38it/s]

-275.5 0.4199000000000639


  6%|████▎                                                                    | 5901/100000 [54:45<21:07:58,  1.24it/s]

-271.8 0.409900000000065


  6%|████▍                                                                    | 6001/100000 [56:04<18:31:39,  1.41it/s]

-273.2 0.3999000000000661


  6%|████▍                                                                    | 6101/100000 [57:23<20:24:45,  1.28it/s]

-272.2 0.3899000000000672


  6%|████▌                                                                    | 6201/100000 [58:43<22:12:05,  1.17it/s]

-269.7 0.3799000000000683


  6%|████▍                                                                  | 6301/100000 [1:00:07<22:21:01,  1.16it/s]

-267.8 0.3699000000000694


  6%|████▌                                                                  | 6401/100000 [1:01:36<22:51:28,  1.14it/s]

-259.1 0.3599000000000705


  7%|████▌                                                                  | 6501/100000 [1:03:09<26:06:18,  1.01s/it]

-259.3 0.3499000000000716


  7%|████▋                                                                  | 6601/100000 [1:04:37<24:39:34,  1.05it/s]

-260.2 0.3399000000000727


  7%|████▊                                                                  | 6701/100000 [1:06:05<24:31:12,  1.06it/s]

-262.5 0.3299000000000738


  7%|████▊                                                                  | 6801/100000 [1:07:37<25:09:05,  1.03it/s]

-254.3 0.3199000000000749


  7%|████▉                                                                  | 6901/100000 [1:09:16<27:49:18,  1.08s/it]

-250.1 0.309900000000076


  7%|████▉                                                                  | 7001/100000 [1:10:55<20:12:21,  1.28it/s]

-247.1 0.2999000000000771


  7%|█████                                                                  | 7101/100000 [1:12:39<27:02:53,  1.05s/it]

-239.6 0.2899000000000782


  7%|█████                                                                  | 7201/100000 [1:14:21<20:17:27,  1.27it/s]

-242.9 0.2799000000000793


  7%|█████▏                                                                 | 7301/100000 [1:16:07<28:26:48,  1.10s/it]

-234.9 0.2699000000000804


  7%|█████▎                                                                 | 7401/100000 [1:17:58<28:43:40,  1.12s/it]

-231.4 0.2599000000000815


  8%|█████▎                                                                 | 7501/100000 [1:19:52<28:14:22,  1.10s/it]

-220.5 0.2499000000000826


  8%|█████▍                                                                 | 7601/100000 [1:21:40<31:18:57,  1.22s/it]

-230.2 0.2399000000000837


  8%|█████▍                                                                 | 7701/100000 [1:23:40<30:03:43,  1.17s/it]

-217.0 0.22990000000008481


  8%|█████▌                                                                 | 7801/100000 [1:25:43<30:05:59,  1.18s/it]

-209.1 0.21990000000008592


  8%|█████▌                                                                 | 7901/100000 [1:27:48<29:48:06,  1.16s/it]

-210.6 0.20990000000008702


  8%|█████▋                                                                 | 8001/100000 [1:29:57<28:59:13,  1.13s/it]

-200.0 0.19990000000008812


  8%|█████▊                                                                 | 8101/100000 [1:32:08<31:47:05,  1.25s/it]

-197.0 0.18990000000008922


  8%|█████▊                                                                 | 8201/100000 [1:34:25<31:43:57,  1.24s/it]

-183.0 0.17990000000009032


  8%|█████▉                                                                 | 8301/100000 [1:36:47<40:08:19,  1.58s/it]

-180.4 0.16990000000009142


  8%|█████▉                                                                 | 8401/100000 [1:39:20<36:52:52,  1.45s/it]

-160.3 0.15990000000009252


  9%|██████                                                                 | 8501/100000 [1:41:49<45:35:21,  1.79s/it]

-164.8 0.14990000000009363


  9%|██████                                                                 | 8601/100000 [1:44:28<55:39:51,  2.19s/it]

-147.1 0.13990000000009473


  9%|██████▏                                                                | 8701/100000 [1:47:08<38:03:34,  1.50s/it]

-142.1 0.12990000000009583


  9%|██████▏                                                                | 8801/100000 [1:50:00<33:11:32,  1.31s/it]

-124.5 0.11990000000009622


  9%|██████▎                                                                | 8901/100000 [1:53:06<46:48:33,  1.85s/it]

-101.5 0.10990000000009593


  9%|██████▍                                                                | 9001/100000 [1:56:32<50:31:01,  2.00s/it]

-63.3 0.09990000000009565


  9%|██████▍                                                                | 9101/100000 [1:59:48<43:43:44,  1.73s/it]

-80.1 0.08990000000009536


  9%|██████▌                                                                | 9201/100000 [2:03:31<70:38:17,  2.80s/it]

-36.4 0.07990000000009508


  9%|██████▌                                                                | 9301/100000 [2:07:13<44:07:25,  1.75s/it]

-32.9 0.06990000000009479


  9%|██████▋                                                                | 9401/100000 [2:11:38<69:29:07,  2.76s/it]

44.7 0.0599000000000945


 10%|██████▋                                                                | 9501/100000 [2:16:23<95:12:38,  3.79s/it]

77.1 0.049900000000094216


 10%|██████▊                                                                | 9601/100000 [2:22:00<84:45:09,  3.38s/it]

178.4 0.03990000000009393


 10%|██████▉                                                                | 9701/100000 [2:27:33<64:22:17,  2.57s/it]

167.7 0.029900000000093692


 10%|██████▉                                                                | 9801/100000 [2:34:12<95:31:18,  3.81s/it]

288.3 0.019900000000093752


 10%|██████▉                                                               | 9901/100000 [2:41:40<242:56:52,  9.71s/it]

385.4 0.009900000000093813


 10%|██████▉                                                              | 10001/100000 [2:51:49<170:50:08,  6.83s/it]

621.6 0.01


 10%|███████                                                               | 10101/100000 [2:59:11<15:49:26,  1.58it/s]

376.6 0.01


 10%|███████                                                              | 10201/100000 [3:05:39<136:24:09,  5.47s/it]

283.4 0.01


 10%|███████▏                                                              | 10301/100000 [3:12:25<78:48:29,  3.16s/it]

315.6 0.01


 10%|███████▎                                                              | 10401/100000 [3:18:30<84:13:03,  3.38s/it]

239.4 0.01


 11%|███████▎                                                              | 10501/100000 [3:24:19<59:33:09,  2.40s/it]

210.2 0.01


 11%|███████▍                                                              | 10601/100000 [3:29:30<81:46:15,  3.29s/it]

141.0 0.01


 11%|███████▍                                                             | 10701/100000 [3:35:45<112:31:04,  4.54s/it]

256.6 0.01


 11%|███████▍                                                             | 10801/100000 [3:42:55<123:58:48,  5.00s/it]

361.5 0.01


 11%|███████▌                                                             | 10901/100000 [3:52:23<124:27:27,  5.03s/it]

375.2 0.01


 11%|███████▌                                                             | 11001/100000 [4:03:01<188:41:11,  7.63s/it]

410.1 0.01


 11%|███████▋                                                             | 11101/100000 [4:13:44<273:38:25, 11.08s/it]

399.2 0.01


 11%|███████▋                                                             | 11201/100000 [4:22:08<104:31:44,  4.24s/it]

239.9 0.01


 11%|███████▊                                                             | 11301/100000 [4:31:22<117:08:22,  4.75s/it]

290.3 0.01


 11%|███████▉                                                              | 11354/100000 [4:37:57<36:10:11,  1.47s/it]


KeyboardInterrupt: 

In [21]:
n_episodes = 1
pbar = tqdm.trange(n_episodes)
for t in pbar:
    env.reset() 
    feature = torch.zeros(feature_len).float()
    epsilon =  epsilon - eps_dec \
            if epsilon > eps_min else eps_min
    score = 0
    while True:
        random_action =  random.random() <= epsilon
        env.new_figure()
        next_state, next_feature, reward, done = simulate_RL(env, random_action)
        score += reward
        replay_memory.append((feature, reward, next_feature, done))
        if done:
            scores.append(score)
            print("///////////Game Over//////////////////")
            break
        env.field = next_state
        env.break_lines()
        print()
        for row in env.field:
            print(row)
        print(next_feature)
        feature = next_feature
print(score)

  0%|                                                                                            | 0/1 [00:00<?, ?it/s]


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
tensor([6., 1., 5., 3., 0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0

tensor([10.,  5., 51.,  7.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([10.,  5., 55.,  7.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


tensor([ 18.,   7., 103.,  14.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([14.,  7., 97., 13.,  1.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 10.,  13., 127.,  14.,   1.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0

[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 10.,  13., 127.,  15.,   1.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 1, 0, 0, 1, 1]
[1, 0, 0, 0, 0, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 18.,  12., 120.,  14.,   1.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0,

tensor([ 12.,  11., 103.,  11.,   1.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 1, 1, 0, 0, 0, 0]
[0, 0, 0, 1, 1, 1, 1, 0, 1, 1]
[0, 0, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 12.,  11., 107.,  12.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 1, 1, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1,

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([20.,  6., 76., 11.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 

tensor([ 22.,   9., 107.,  14.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 1, 0, 0, 0]
[1, 1, 1, 1, 0, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 0, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 18.,   9., 111.,  14.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 1,

tensor([ 12.,  11., 103.,  12.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[1, 0, 0, 1, 1, 1, 0, 0, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([12., 11., 97., 11.,  1.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 1

tensor([14.,  8., 76.,  9.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 0, 0, 1, 1, 0, 0]
[1, 1, 1, 1, 0, 0, 1, 1, 1, 0]
[1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([18.,  8., 80.,  9.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


tensor([16.,  8., 96., 11.,  0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 0]
[1, 1, 0, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 20.,   8., 100.,  12.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0

tensor([ 12.,  12., 110.,  13.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 1, 1, 1, 0, 0, 1, 1]
[1, 0, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 12.,  12., 114.,  13.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 1, 1, 1, 0,

tensor([ 12.,  12., 122.,  13.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[0, 0, 0, 1, 1, 1, 1, 0, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 12.,  12., 126.,  14.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 0, 1, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 1, 1, 1, 1, 1,

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]

tensor([ 18.,  14., 130.,  14.,   1.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0, 1, 1, 0]
[1, 1, 1, 0, 1, 0, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 1, 0, 1, 1]
tensor([ 18.,  14., 134.,  14.,   0.])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 1, 1, 0, 1, 1, 0]
[1, 1, 1, 0, 1, 0, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 1, 1, 1, 1, 1,

In [37]:
t = Tetris(20,10)

while True:
    sentence = input("Input:")
    if sentence =="q":
        break
    if t.figure is None:
        t.new_figure()
    if sentence == "u":
        t.rotate()
    elif sentence == "l":
        t.go_side(-1)
    elif sentence == "r":
        t.go_side(1)
    elif sentence == "s":
        t.go_space()
    print(simulate(t))
    t.go_down()
    print()
    for row in t.field:
        print(row)

Input:q


In [10]:
# Initialize the game engine
pygame.init()

# Define some colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GRAY = (128, 128, 128)

size = (400, 500)
screen = pygame.display.set_mode(size)

pygame.display.set_caption("Tetris")

# Loop until the user clicks the close button.
done = False
clock = pygame.time.Clock()
fps = 10
game = Tetris(20, 10)
counter = 0

pressing_down = False

while not done:
    if game.figure is None:
        game.new_figure()
    counter += 1
    if counter > 100000:
        counter = 0

    if counter % (fps // game.level // 2) == 0 or pressing_down:
        if not game.done:
            game.go_down()

    for event in list(pygame.event.get()) + run_ai(game):
        if event.type == pygame.QUIT:
            done = True
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_UP:
                game.rotate()
            if event.key == pygame.K_DOWN:
                pressing_down = True
            if event.key == pygame.K_LEFT:
                game.go_side(-1)
            if event.key == pygame.K_RIGHT:
                game.go_side(1)
            if event.key == pygame.K_SPACE:
                game.go_space()
            if event.key == pygame.K_ESCAPE:
                game.__init__(20, 10)

    if event.type == pygame.KEYUP:
            if event.key == pygame.K_DOWN:
                pressing_down = False

    screen.fill(WHITE)

    for i in range(game.height):
        for j in range(game.width):
            pygame.draw.rect(screen, GRAY, [game.x + game.zoom * j, game.y + game.zoom * i, game.zoom, game.zoom], 1)
            if game.field[i][j] > 0:
                pygame.draw.rect(screen, colors[game.field[i][j]],
                                 [game.x + game.zoom * j + 1, game.y + game.zoom * i + 1, game.zoom - 2, game.zoom - 1])
    
    if game.figure is not None:
        for i in range(4):
            for j in range(4):
                p = i * 4 + j
                if p in game.figure.image():
                    pygame.draw.rect(screen, colors[game.figure.color],
                                     [game.x + game.zoom * (j + game.figure.x) + 1,
                                      game.y + game.zoom * (i + game.figure.y) + 1,
                                      game.zoom - 2, game.zoom - 2])

    font = pygame.font.SysFont('Calibri', 25, True, False)
    font1 = pygame.font.SysFont('Calibri', 65, True, False)
    text = font.render("Score: " + str(game.score), True, BLACK)
    text_game_over = font1.render("Game Over", True, (255, 125, 0))
    text_game_over1 = font1.render("Press ESC", True, (255, 215, 0))

    screen.blit(text, [0, 0])
    if game.done:
        screen.blit(text_game_over, [20, 200])
        screen.blit(text_game_over1, [25, 265])

    pygame.display.flip()
    clock.tick(fps)

pygame.quit()